version: '2'
services:

  jenkins:
    build: ./jenkins
    volumes_from:
      - workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./blueocean_home:/var/jenkins_home
    ports:
      - 8888:8080
      - 4444:4040

  workspace:
    image: alpine:3.5
    volumes:
      - /opt/jenkins/data/workspace
